// let form = document.createElement("form");
// console.log(form);
// let username = document.createElement("username");
// username.setAttribute("type", "text");
// username.setAttribute("name", "username");
// username.setAttribute("placeholder", "enter name");
// console.log(username);
// username.value = "jothika";
// let email = document.createElement("email");
// nameInput.setAttribute("type", "email");
// nameInput.setAttribute("name", "email");
// nameInput.setAttribute("placeholder", "email");
// let submitbtn = document.createElement("button");
// console.log(button);
// nameInput.setAttribute("type", "submit");
// document.appendChild(form);
// form.appendChild(username);
// form.appendChild(email);
// form.appendChild(submit);
